server:
  port: 8090

spring:

  redis:
    port: 6379
    password:
    lettuce:
      pool:
        max-idle: 10
        max-active: 1000
        max-wait: -1
        min-idle: 0
    timeout: 3000
    sentinel: #哨兵模式
      master: mymaster #主服务器所在集群名称
      nodes: 10.1.20.73:26379,10.1.20.73:26380,10.1.20.73:26381 #配置的是sentinel节点IP
