server:
  port: 8090

spring:

  redis:
    host: 127.0.0.1
    port: 6379
#    password:
    lettuce:
      pool:
        max-idle: 10
        max-active: 1000
        max-wait: -1
        min-idle: 0
    timeout: 6000
    redisson:
      singleServerConfig:
        idleConnectionTimeout: 10000
        connectTimeout: 10000
        timeout: 3000
        retryAttempts: 3
        retryInterval: 1500
        password: ${spring.redis.password}
        subscriptionsPerConnection: 5
        clientName: redisson
        address: redis://${spring.redis.host}:${spring.redis.port}
        subscriptionConnectionMinimumIdleSize: 1
        subscriptionConnectionPoolSize: 50
        connectionMinimumIdleSize: 32
        connectionPoolSize: 64
        database: 0
        dnsMonitoringInterval: 5000
      codec: org.redisson.codec.JsonJacksonCodec
      transportMode: "NIO"
